# Generated by Django 5.0.2 on 2024-03-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart_id',
            new_name='cartt',
        ),
    ]
