# Generated by Django 5.0.2 on 2024-03-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_cart_id_order_cartt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Return')], default=2),
            preserve_default=False,
        ),
    ]
